services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development # Clarity and Explicitness
      TZ: "America/Vancouver"
    command: sh -c "npm install -g nodemon && npm install && npm run dev "

  mongodb:
    image: mongo:7.0.8
    restart: always
    environment:
      TZ: "America/Vancouver"
    command: mongod --noauth
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27019:27017


  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
      ME_CONFIG_BASICAUTH: false
      TZ: "America/Vancouver"
    links:
      - mongodb

  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   environment:
  #     TZ: "America/Vancouver"
  #   command: redis-server --save 60 1 --loglevel warning

volumes:
  # redis_data:
  mongodb_data:
  
